# Generated by Django 4.1 on 2022-09-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_score_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ('game_type', '-score', 'duration')},
        ),
        migrations.AddField(
            model_name='score',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
