# Generated by Django 4.1 on 2022-09-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_score_options_score_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ('game_type', 'game_sub_type', '-score', 'duration')},
        ),
        migrations.AddField(
            model_name='score',
            name='game_sub_type',
            field=models.IntegerField(choices=[(1, 'World'), (2, 'North America'), (3, 'South America'), (4, 'Europe'), (5, 'Africa'), (6, 'Asia'), (7, 'Oceania')], default=1),
        ),
        migrations.AlterField(
            model_name='score',
            name='game_type',
            field=models.IntegerField(choices=[(1, 'Random Map'), (2, 'Free Guessing')], default=1),
        ),
    ]
